spring.application.name=bambeli-api
server.port=8080

spring.datasource.url=jdbc:sqlite:bambeli.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=warn

bambeli.jwt.secret=BambeliSecretKeyForJwtCourseProject2026WithEnoughLength
bambeli.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
